// ─────────────────────────────────────────────────────────────
//  TEMPLATES
// ─────────────────────────────────────────────────────────────
const TPLS = {
    ecommerce: { title: "E-Commerce", nodes: [{ id: "c", type: "person", label: "Customer", desc: "Online shopper", x: 220, y: 60 }, { id: "a", type: "person", label: "Admin", desc: "Store manager", x: 540, y: 60 }, { id: "w", type: "system", label: "E-Commerce App", desc: "Web + API", x: 370, y: 215 }, { id: "p", type: "external", label: "Stripe", desc: "Payments", x: 640, y: 370 }, { id: "em", type: "external", label: "SendGrid", desc: "Email", x: 120, y: 370 }, { id: "wh", type: "external", label: "Warehouse", desc: "Inventory", x: 370, y: 435 }, { id: "db", type: "database", label: "Products DB", desc: "PostgreSQL", x: 650, y: 215 }], edges: [{ src: "c", tgt: "w", label: "orders" }, { src: "a", tgt: "w", label: "manages" }, { src: "w", tgt: "p", label: "charges" }, { src: "w", tgt: "em", label: "notifies" }, { src: "w", tgt: "wh", label: "updates" }, { src: "w", tgt: "db", label: "reads/writes" }] },
    banking: { title: "Online Banking", nodes: [{ id: "c", type: "person", label: "Customer", desc: "Retail/business", x: 250, y: 60 }, { id: "o", type: "person", label: "Bank Officer", desc: "Internal staff", x: 590, y: 60 }, { id: "b", type: "system", label: "Banking System", desc: "Core platform", x: 415, y: 205 }, { id: "core", type: "external", label: "Core Banking", desc: "Mainframe", x: 700, y: 340 }, { id: "sw", type: "external", label: "SWIFT", desc: "Wire transfer", x: 555, y: 450 }, { id: "fr", type: "external", label: "Fraud API", desc: "ML detection", x: 200, y: 410 }, { id: "db", type: "database", label: "Accounts DB", desc: "Oracle", x: 110, y: 205 }], edges: [{ src: "c", tgt: "b", label: "transfers" }, { src: "o", tgt: "b", label: "manages" }, { src: "b", tgt: "core", label: "account ops" }, { src: "b", tgt: "sw", label: "wire" }, { src: "b", tgt: "fr", label: "validates" }, { src: "b", tgt: "db", label: "reads/writes" }] },
    microservices: { title: "Microservices", nodes: [{ id: "cli", type: "person", label: "Client", desc: "Web/Mobile", x: 400, y: 55 }, { id: "gw", type: "container", label: "API Gateway", desc: "Kong", x: 400, y: 165 }, { id: "auth", type: "container", label: "Auth Service", desc: "JWT", x: 150, y: 290 }, { id: "usr", type: "container", label: "User Service", desc: "Node.js", x: 375, y: 290 }, { id: "ord", type: "container", label: "Order Service", desc: "Go", x: 585, y: 290 }, { id: "mq", type: "database", label: "RabbitMQ", desc: "Queue", x: 585, y: 420 }, { id: "dbu", type: "database", label: "Users DB", desc: "Postgres", x: 205, y: 420 }, { id: "dbo", type: "database", label: "Orders DB", desc: "Mongo", x: 455, y: 420 }, { id: "ntf", type: "container", label: "Notify", desc: "Python", x: 770, y: 290 }], edges: [{ src: "cli", tgt: "gw", label: "HTTPS" }, { src: "gw", tgt: "auth", label: "validate" }, { src: "gw", tgt: "usr", label: "route" }, { src: "gw", tgt: "ord", label: "route" }, { src: "ord", tgt: "mq", label: "publish" }, { src: "mq", tgt: "ntf", label: "consume" }, { src: "usr", tgt: "dbu", label: "read/write" }, { src: "ord", tgt: "dbo", label: "read/write" }] },
    saas: { title: "SaaS Platform", nodes: [{ id: "u", type: "person", label: "Tenant User", desc: "End-user", x: 325, y: 55 }, { id: "adm", type: "person", label: "Admin", desc: "Operator", x: 130, y: 55 }, { id: "cdn", type: "container", label: "CDN/WAF", desc: "CloudFront", x: 325, y: 155 }, { id: "spa", type: "container", label: "React SPA", desc: "Frontend", x: 200, y: 275 }, { id: "api", type: "container", label: "REST API", desc: "NestJS", x: 485, y: 275 }, { id: "db", type: "database", label: "Postgres", desc: "Multi-tenant", x: 665, y: 385 }, { id: "cache", type: "database", label: "Redis", desc: "Cache", x: 395, y: 405 }, { id: "s3", type: "external", label: "S3", desc: "Storage", x: 175, y: 400 }, { id: "stripe", type: "external", label: "Stripe", desc: "Billing", x: 665, y: 155 }], edges: [{ src: "u", tgt: "cdn", label: "HTTPS" }, { src: "cdn", tgt: "spa", label: "serves" }, { src: "spa", tgt: "api", label: "REST" }, { src: "api", tgt: "db", label: "read/write" }, { src: "api", tgt: "cache", label: "cache" }, { src: "api", tgt: "s3", label: "upload" }, { src: "api", tgt: "stripe", label: "billing" }, { src: "adm", tgt: "api", label: "manages" }] }
};
function loadTpl(name) {
    const t = TPLS[name]; if (!t) return;
    renderJSON(t);
    addMsg('ai', '📐 <b>' + t.title + '</b><br><small>Hover line → kéo segment  ·  Kéo ● bend  ·  Dbl-click ● xóa</small><div class="chips"><button class="chip g" onclick="autoLayout()">⟳ Layout</button><button class="chip" onclick="qmsg(\'Drill into: ' + t.title + '\')">→ Drill</button></div>');
}
